name: Deploy to VPS

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            source ~/.bashrc
            cd ~/gov-api
            git pull origin main
            pnpm install
            pnpm run build
            pm2 reload gov-api || pm2 start dist/main.js --name gov-api --time
